INCLUDE:
  - conf/dev/global/log.yaml
cam_list:
  - conf/dev/cam/count_face/stream1.yaml  # 计数+人脸（依赖face服务）
#  - conf/dev/cam/helmet/stream2.yaml  # 安全帽
#  - conf/dev/cam/phone/stream3.yaml  # 手机
#  - conf/dev/cam/card/stream5.yaml  # 代刷卡
#  - conf/dev/cam/intrude/stream5.yaml  # 入侵检测
service: [] # 全局服务
#  - path: lib/face/insight_module/insight/zero/component/insight_comp.py
#    conf: conf/dev/algorithm/face/insight/insight.yaml

