INCLUDE:
  - conf/dev/global/config.yaml

# 全局服务
service_list: []

# 视频流
stream_list:
  - path: lib/zero/core/stream_comp.py
    conf: conf/dev/stream/stream1.yaml

# 算法
algorithm_list:
#  # 示例1.打印视频流
#  - path: examples/p1_empty_stream_comp.py
#    conf: conf/dev/examples/p1_empty_stream.yaml
  # 示例2.目标检测
  - path: lib/detection/yolox/zero/yolox_comp.py
    conf: conf/dev/algorithm/yolox/yolox_person.yaml

app:
  running_file: bin/dev/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_enable: True  # 是否打印性能分析报告
  analysis_interval: 5  # 每隔x秒打印一次性能分析报告

update_fps: 1  # 主进程更新帧率