INCLUDE:
  - conf/dev/global/config.yaml

# 全局服务
service_list:
#  - path: lib/facr/insight/zero/component/insight_comp.py
#    conf: conf/dev/service/facr/insight/insight.yaml
  - path: lib/reid/reid_core/reid_comp.py
    conf: conf/dev/service/reid/clip_reid.yaml

# 视频流
stream_list:
  - path: lib/zero/core/stream_comp.py
    conf: conf/dev/stream/stream1.yaml

# 算法
algorithm_list:
  # --------- 算法 ---------
  - path: lib/detection/yolox/zero/yolox_comp.py
    conf: conf/dev/algorithm/yolox/yolox_person.yaml
  # --------- 业务 ---------
#  - path: src/p3_hello_world_comp.py
#    conf: ""
#  - path: src/p4_hello_comp.py
#    conf: conf/dev/feature/p4_hello.yaml
#  - path: src/p5_get_stream_comp.py
#    conf: conf/dev/feature/p5_get_stream.yaml
#  - path: src/p6_det_test_comp.py
#    conf: conf/dev/feature/p6_det_test.yaml
#  - path: src/p7_mot_test_comp.py
#    conf: conf/dev/feature/p7_mot_test.yaml
#  - path: src/p8_facr_test_comp.py
#    conf: conf/dev/feature/p8_facr_test.yaml
  - path: src/p9_reid_test_comp.py
    conf: conf/dev/feature/p9_reid_test.yaml


app:
  running_file: bin/dev/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_enable: True  # 是否打印性能分析报告
  analysis_interval: 5  # 每隔x秒打印一次性能分析报告

update_fps: 1  # 主进程更新帧率