INCLUDE:
  - conf/pro/global/config.yaml

# 全局服务
service_list:
  - path: lib/network/simple_http/simple_http_comp.py  # HTTP服务
    conf: conf/pro/service/http/http.yaml
  - path: lib/facr/insight/zero/component/insight_comp.py  # 人脸识别服务
    conf: conf/pro/service/facr/insight/insight.yaml
  - path: lib/reid/reid_core/reid_comp.py  # reid服务
    conf: conf/pro/service/reid/clip_reid.yaml
  - path: lib/reid/reid_core/reid_search_person_comp.py  # 找人服务
    conf: conf/pro/service/reid/search_person.yaml

# 视频流
stream_list:
  - path: lib/zero/core/stream_comp.py  # 111: 计数
    conf: conf/pro/stream/stream1.yaml
  - path: lib/zero/core/stream_comp.py  # 120: 手机（找人）
    conf: conf/pro/stream/stream2.yaml
  - path: lib/zero/core/stream_comp.py  # 113: 代刷卡
    conf: conf/pro/stream/stream3.yaml
  - path: lib/zero/core/stream_comp.py  # 116: 入侵
    conf: conf/pro/stream/stream4.yaml
  - path: lib/zero/core/stream_comp.py  # 14: 人脸
    conf: conf/pro/stream/stream5.yaml
  - path: lib/zero/core/stream_comp.py # 16: 手机（屏幕左边）
    conf: conf/pro/stream/stream6.yaml
  # - path: lib/zero/core/stream_comp.py # 117: 手机（屏幕正对面）
  #   conf: conf/pro/stream/stream7.yaml
  - path: lib/zero/core/stream_comp.py # 118: 手机（屏幕上方）
    conf: conf/pro/stream/stream8.yaml
  - path: lib/zero/core/stream_comp.py # 12: 手机（屏幕斜对面）
    conf: conf/pro/stream/stream9.yaml

# 算法
algorithm_list:
  # ------------------- 目标检测算法 -------------------
  # - path: lib/detection/yolox/zero/yolox_comp.py  # 计数
  #   conf: conf/pro/algorithm/yolox/yolox_count.yaml
  - path: lib/detection/yolox/zero/yolox_comp.py  # 人1
    conf: conf/pro/algorithm/yolox/yolox_person1.yaml
  - path: lib/detection/yolox/zero/yolox_comp.py  # 人2
    conf: conf/pro/algorithm/yolox/yolox_person2.yaml
  # - path: lib/detection/yolox/zero/yolox_comp.py  # 安全帽
  #   conf: conf/pro/algorithm/yolox/yolox_helmet.yaml
  # - path: lib/detection/yolox/zero/yolox_comp.py  # 手机
  #   conf: conf/pro/algorithm/yolox/yolox_phone.yaml
  # ------------------- 视频异常检测算法 -------------------
#  - path: lib/vad/vad_core/vad_comp.py
#    conf: conf/pro/algorithm/vad_mae/config.yaml

  # ------------------- 业务算法 -------------------
  # - path: src/count/count_comp.py  # 计数 (计数检测)
  #   conf: conf/pro/feature/count/count1.yaml
  # - path: src/renlian/renlian_comp.py  # 人脸 (人检测)
  #   conf: conf/pro/feature/renlian/renlian1.yaml
  - path: src/intrude/intrude_comp.py  # 入侵 (人检测+人脸服务)
    conf: conf/pro/feature/intrude/intrude1.yaml
  # - path: src/helmet/helmet_comp.py  # 安全帽 (人检测+安全帽检测)
  #   conf: conf/pro/feature/helmet/helmet1.yaml
  # - path: src/card/card_comp.py # 代刷卡 (人)
  #   conf: conf/pro/feature/card/card1.yaml
  # - path: src/phone/phone_comp.py
  #   conf: conf/pro/feature/phone/phone2.yaml
  # - path: src/phone/phone_comp.py
  #   conf: conf/pro/feature/phone/phone6.yaml
  # - path: src/phone/phone_comp.py  # 手机 (人+手机+reid服务)
  #   conf: conf/pro/feature/phone/phone8.yaml
  # - path: src/phone/phone_comp.py
  #   conf: conf/pro/feature/phone/phone9.yaml

app:
  running_file: bin/pro/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_enable: True  # 是否打印性能分析报告
  analysis_interval: 300  # 每隔x秒打印一次性能分析报告

update_fps: 1  # 主进程更新帧率