INCLUDE:
  - conf/dev/global/config.yaml

# 全局服务
service_list:
  - path: lib/network/simple_http/simple_http_comp.py  # HTTP服务
    conf: conf/dev/service/http/http.yaml
#  - path: lib/facr/insight/zero/component/insight_comp.py  # 人脸识别服务
#    conf: conf/dev/service/facr/insight/insight.yaml

# 视频流
stream_list:
  - path: lib/zero/core/stream_comp.py
    conf: conf/dev/stream/stream1.yaml

# 算法
algorithm_list:
  # ------------------- 目标检测算法 -------------------
  - path: lib/detection/yolox/zero/yolox_comp.py  # 人
    conf: conf/dev/algorithm/yolox/yolox_person.yaml
  - path: lib/detection/yolox/zero/yolox_comp.py  # 安全帽
    conf: conf/dev/algorithm/yolox/yolox_helmet.yaml
  # ------------------- 业务算法 -------------------
#  - path: src/count/count_comp.py  # 计数
#    conf: conf/dev/feature/count/count1.yaml
#  - path: src/renlian/renlian_comp.py  # 人脸
#    conf: conf/dev/feature/renlian/renlian1.yaml
#  - path: src/card/card_comp.py  # 代刷卡
#    conf: conf/dev/feature/card/card1.yaml
  - path: src/helmet/helmet_comp.py  # 安全帽
    conf: conf/dev/feature/helmet/helmet1.yaml

app:
  running_file: bin/dev/runtime.pkl  # 框架运行时标识路径，运行时生成，删除该文件可以关闭算法端
  analysis_enable: True  # 是否打印性能分析报告
  analysis_interval: 5  # 每隔x秒打印一次性能分析报告

update_fps: 1  # 主进程更新帧率