INCLUDE:
  - conf/pro/algorithm/yolox/labels/person_labels.yaml

bytetrack:
  args:
    fps: 30 # frame rate (fps)
    thresh: 0.5 # tracking confidence threshold
    buffer: 30 # the frames for keep lost tracks
    match_thresh: 0.8 # matching threshold for tracking
    aspect_ratio_thresh: 5 # threshold for filtering out boxes of which aspect ratio are above the given value.
    min_box_area: 5 # filter out tiny boxes
    mot20: False
  reid:
    enable: False  # 是否支持reid存图(若支持，会定期对第0个类别发送reid存图请求)
    conf: 0.7  # 是否支持reid存图(若支持，会定期对第0个类别发送reid存图请求)
    min_interval: 300  # reid存图最小间隔(支持reid存图才有效)
    max_interval: 3600  # reid存图最大间隔(支持reid存图才有效)
    lost_frames: 180  # 对象消失多少帧则销毁
    camera_gallery: output/service/clip_reid/camera_gallery  # 存图路径(支持reid存图才有效)